#!/bin/bash

# Parse the environment variables and auto-create the default.vcl file
/parse

# Start varnish and log
varnishd -f /etc/varnish/default.vcl -s ${VARNISH_STORAGE_BACKEND} -a 0.0.0.0:${VARNISH_PORT}
varnishlog
